name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**/README.md"
      - "docs/**"
      - "extras/**"
      - "pcb/**"
      - "tools/**"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      SSID: test_ssid
      PASSWORD: test_password
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src, rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: ./ci/check.sh